export const productsArray = [
  {
    id: 0,
    title: "Товар 1",
    price: "170",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
  {
    id: 1,
    title: "Товар 2",
    price: "171",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
  {
    id: 2,
    title: "Товар 3",
    price: "172",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
  {
    id: 3,
    title: "Товар 4",
    price: "173",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
  {
    id: 4,
    title: "Товар 5",
    price: "174",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
  {
    id: 5,
    title: "Товар 6",
    price: "175",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    link: "./product.html",
    image: "./media/image/item.jpg",
  },
];
